In [16]:
import numpy as np
import matplotlib.pyplot as plt

## Save and load

In [10]:
arr1 = np.array([2,3,4,5,1,4])
arr2 = np.floor( np.random.random((3,3))*100 )

np.save('./arrays/array1.npy' , arr1)
np.save('./arrays/array2.npy' , arr2)


In [14]:
loadedArr1 = np.load("./arrays/array1.npy")
print(loadedArr1)

[2 3 4 5 1 4]


In [36]:
arr2d = np.random.random((3,3)) * 100
print(arr2d)
print("\n")

ans = np.where(arr2d > 50)
print(arr2d[ans])
print("\n")

ans2 = np.where( arr2d > 50 , "selected" , "rejected")
print(ans2)


[[61.51238936 54.52685837  1.40161994]
 [73.64355219 52.88982258 23.02376317]
 [40.51728563 19.28442736 32.58263162]]


[61.51238936 54.52685837 73.64355219 52.88982258]


[['selected' 'selected' 'rejected']
 ['selected' 'selected' 'rejected']
 ['rejected' 'rejected' 'rejected']]
