## Numpy arrays and basics

In [2]:
import numpy as np

## Creating arrays from list

In [5]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
arr2D = np.array([[1,3,5] , [2,4,6]])
print(arr2D)


[[1 3 5]
 [2 4 6]]


In [9]:
list1 = [10, 20, 30, 40, 50]
print(list1)

print(list1 * 2)  # This will repeat the list elements i.e multiplication is list is not element wise

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


In [10]:
print(arr1D * 2)  # This will multiply each element by 2 i.e element wise multiplication

[ 2  4  6  8 10]


### List vs Array in np which is faster

In [1]:
import time

time1 = time.time()
list2 = [ i*2 for i in range(1, 1000000)]
print("Time taken by list comprehension: ", time.time() - time1)

Time taken by list comprehension:  0.06809592247009277


In [7]:
time1 = time.time()
arr3= np.arange(1, 1000000) * 2   # Arange creates an array with values from start to end-1
print("Time taken by numpy array operation: ", time.time() - time1)

Time taken by numpy array operation:  0.003999233245849609


### Creating matrices of any number

In [8]:
zero = np.zeros((3,4))  # 3 rows and 4 columns
print("Matrix of zeros:\n", zero)

Matrix of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
one = np.ones((2,5))
print("Matrix of ones:\n", one)

Matrix of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# Matrix of any number
mat = np.full((3,3) , 8)
print("Matrix of 8s:\n", mat)

Matrix of 8s:
 [[8 8 8]
 [8 8 8]
 [8 8 8]]


In [3]:
#Matrix of random number 
random = np.random.random((3,3))
print("Matrix of random numbers:\n", random * 100)

Matrix of random numbers:
 [[63.98053981  8.49411724 47.34118087]
 [41.61259409  7.74283951 59.53729084]
 [24.75174856 39.84002166  5.44769997]]


### Array Reshaping

In [4]:
arr4 = np.arange(12)
print("Original array:\n", arr4)

reshaped = arr4.reshape((3,4))
print("Reshaped array (3x4):\n", reshaped)

flatend = reshaped.flatten()                # Flatten returns a flattened array as a copy   
print("Flattened array:\n", flatend)

raveled = reshaped.ravel()                  # Ravel returns a flattened array but as a original
print("Raveled array:\n", raveled)

transposed = reshaped.T
print("Transposed array:\n", transposed)


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
