## Advance operations with examples

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(sales_data[0:4])  # prints the top 4 data
print("\n")

print(sales_data[:,1:])     # prints all rows and columns from index 1 onwards

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]]


[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [17]:
# print sum of array column wise
sum = np.sum(sales_data , axis=0)
print(sum)

[     15  810000  945000 1085000 1240000]


In [18]:
sum_per_year = np.sum(sales_data[: , 1:3] , axis=0)
print(sum_per_year)

[810000 945000]
