## NumPy Array Operations

In [1]:
import numpy as np

In [3]:
#slicing
arr = np.array([3, 4,2 ,6 ,4,4 ,7,4])
print(arr[2:5])

[2 6 4]


In [19]:
#indexing in 2d array
arr2d = np.floor(np.random.random((3,3))* 100)
print(arr2d)

print(arr2d[1,2])    # 2nd index element of index 1 row
print(arr2d[1])      # entire 1st index row
print(arr2d[:,2])   # entire 2nd index column

[[52. 48. 18.]
 [53. 72. 64.]
 [90. 26. 79.]]
64.0
[53. 72. 64.]
[18. 64. 79.]


## Sorting

In [23]:
# 1d array sorting 
print("sorted array:", np.sort(arr))

# 2d array sorting
print("original 2d array:\n", arr2d)
print("sorted 2d array along rows:\n", np.sort(arr2d, axis=1))
print("sorted 2d array along columns:\n", np.sort(arr2d, axis=0))

sorted array: [2 3 4 4 4 4 6 7]
original 2d array:
 [[52. 48. 18.]
 [53. 72. 64.]
 [90. 26. 79.]]
sorted 2d array along rows:
 [[18. 48. 52.]
 [53. 64. 72.]
 [26. 79. 90.]]
sorted 2d array along columns:
 [[52. 26. 18.]
 [53. 48. 64.]
 [90. 72. 79.]]


## Filter

In [32]:
# In numpy , arrays can also use mask i.e expressions for indexing

newArr = np.array([10, 15, 20, 25, 30, 35, 40])
mask = newArr > 25
print(newArr[mask])

# here we passed an expression as index in an array which lead to solving the expression and gave us output

[30 35 40]


## Where 

In [38]:
# we can use "where" to implement a condition just like mask

res = np.where(newArr > 20)
print(newArr[res])


[25 30 35 40]


In [ ]:
# we can say that "where" works as if else clause
# here , we write it as 
# if newArr > 20 
# print newArr*2
# else newArr

res2 = np.where( newArr > 20 , newArr * 2 , newArr )
print(res2)

[10 15 20 50 60 70 80]


## Array compatibility

In [46]:
arr3 = np.array([3,4,6])
arr4 = np.array([4,2,6])
arr5 = np.array([2])

print(arr3.shape == arr4.shape)
print(arr3.shape == arr5.shape)

True
False


## Adding elements to an array

In [ ]:
a = np.array([[ 2 ,4 ,5],
             [2,7,1]])
print(a)
addRow = np.vstack((a , np.array([3,1,8]) ))                 # used to add row
print("After adding row :\n" , addRow)

addCol = np.hstack( (a , np.array([[2] , [2]]) ))
print("After adding col :\n" , addCol)


[[2 4 5]
 [2 7 1]]
After adding row :
 [[2 4 5]
 [2 7 1]
 [3 1 8]]


TypeError: Field elements must be 2- or 3-tuples, got '2'